import type { ProductRow } from "./product-form";
import { svgCardImage } from "./product-utils";

export const DUMMY_PRODUCTS: ProductRow[] = [
  {
    id: "PRD-0001",
    name: "Nova Phone X",
    description: "Flagship smartphone with pro camera and AMOLED display",
    category: { key: "electronics", label: "Electronics" },
    brand: "Nova",
    price: 799.0,
    stock: 42,
    status: "Active",
    createdAt: "2025-12-14T10:15:00Z",
    image: svgCardImage("Flagship smartphone"),
    images: [svgCardImage("Flagship smartphone")],
  },
  {
    id: "PRD-0002",
    name: "Acme Laptop Pro",
    description: "High-performance laptop for creators and developers",
    category: { key: "electronics", label: "Electronics" },
    brand: "Acme",
    price: 1199.99,
    stock: 18,
    status: "Active",
    createdAt: "2025-12-13T12:05:00Z",
    image: svgCardImage("High-performance laptop"),
    images: [svgCardImage("High-performance laptop")],
  },
  {
    id: "PRD-0003",
    name: "Evergreen Blender",
    description: "Powerful blender for smoothies, soups, and sauces",
    category: { key: "home", label: "Home & Kitchen" },
    brand: "Evergreen",
    price: 89.99,
    stock: 0,
    status: "Inactive",
    createdAt: "2025-12-10T15:42:00Z",
    image: svgCardImage("Powerful blender"),
    images: [svgCardImage("Powerful blender")],
  },
  {
    id: "PRD-0004",
    name: "Chef Pan Set",
    description: "Durable non-stick cookware set for everyday cooking",
    category: { key: "home", label: "Home & Kitchen" },
    brand: "Acme",
    price: 129.5,
    stock: 73,
    status: "Active",
    createdAt: "2025-12-08T09:20:00Z",
    image: svgCardImage("Non-stick cookware"),
    images: [svgCardImage("Non-stick cookware")],
  },
  {
    id: "PRD-0005",
    name: "Zenith Jacket",
    description: "Weather-resistant jacket with warm lining",
    category: { key: "fashion", label: "Fashion" },
    brand: "Zenith",
    price: 159.0,
    stock: 11,
    status: "Inactive",
    createdAt: "2025-12-07T18:11:00Z",
    image: svgCardImage("Weather-resistant jacket"),
    images: [svgCardImage("Weather-resistant jacket")],
  },
  {
    id: "PRD-0006",
    name: "Pulse Running Shoes",
    description: "Lightweight shoes designed for daily running",
    category: { key: "sports", label: "Sports" },
    brand: "Pulse",
    price: 129.5,
    stock: 73,
    status: "Active",
    createdAt: "2025-12-06T10:15:00Z",
    image: svgCardImage("Running shoes"),
    images: [svgCardImage("Running shoes")],
  },
  {
    id: "PRD-0007",
    name: "Outdoor Trek Bottle",
    description: "Insulated water bottle for hiking and travel",
    category: { key: "sports", label: "Sports" },
    brand: "Vertex",
    price: 24.0,
    stock: 132,
    status: "Active",
    createdAt: "2025-12-05T08:33:00Z",
    image: svgCardImage("Insulated bottle"),
    images: [svgCardImage("Insulated bottle")],
  },
  {
    id: "PRD-0008",
    name: "Glow Serum",
    description: "Brightening facial serum with vitamin C",
    category: { key: "beauty", label: "Beauty" },
    brand: "Evergreen",
    price: 49.0,
    stock: 22,
    status: "Active",
    createdAt: "2025-12-04T11:02:00Z",
    image: svgCardImage("Brightening serum"),
    images: [svgCardImage("Brightening serum")],
  },
  {
    id: "PRD-0009",
    name: "Noir Fragrance",
    description: "Long-lasting fragrance with woody notes",
    category: { key: "beauty", label: "Beauty" },
    brand: "Nova",
    price: 79.0,
    stock: 6,
    status: "Inactive",
    createdAt: "2025-12-03T12:47:00Z",
    image: svgCardImage("Woody fragrance"),
    images: [svgCardImage("Woody fragrance")],
  },
  {
    id: "PRD-0010",
    name: "Fiction Bestseller",
    description: "Bestselling novel with suspense and drama",
    category: { key: "books", label: "Books" },
    brand: "Acme",
    price: 19.99,
    stock: 250,
    status: "Active",
    createdAt: "2025-12-02T09:20:00Z",
    image: svgCardImage("Bestselling novel"),
    images: [svgCardImage("Bestselling novel")],
  },
  {
    id: "PRD-0011",
    name: "Non-fiction Guide",
    description: "Practical guide for productivity and habits",
    category: { key: "books", label: "Books" },
    brand: "Zenith",
    price: 22.99,
    stock: 80,
    status: "Active",
    createdAt: "2025-12-01T14:09:00Z",
    image: svgCardImage("Productivity guide"),
    images: [svgCardImage("Productivity guide")],
  },
  {
    id: "PRD-0012",
    name: "Nova Dress",
    description: "Elegant dress suitable for events and parties",
    category: { key: "fashion", label: "Fashion" },
    brand: "Nova",
    price: 99.0,
    stock: 15,
    status: "Active",
    createdAt: "2025-11-30T10:15:00Z",
    image: svgCardImage("Elegant dress"),
    images: [svgCardImage("Elegant dress")],
  },
];
